/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AmcRouteImport } from './routes/amc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmNewRouteImport } from './routes/crm_.new'
import { Route as CrmIdEditRouteImport } from './routes/crm_.$id.edit'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AmcRoute = AmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmNewRoute = CrmNewRouteImport.update({
  id: '/crm_/new',
  path: '/crm/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIdEditRoute = CrmIdEditRouteImport.update({
  id: '/crm_/$id/edit',
  path: '/crm/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/technicians': typeof TechniciansRoute
  '/warranty': typeof WarrantyRoute
  '/crm/new': typeof CrmNewRoute
  '/crm/$id/edit': typeof CrmIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/technicians': typeof TechniciansRoute
  '/warranty': typeof WarrantyRoute
  '/crm/new': typeof CrmNewRoute
  '/crm/$id/edit': typeof CrmIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/technicians': typeof TechniciansRoute
  '/warranty': typeof WarrantyRoute
  '/crm_/new': typeof CrmNewRoute
  '/crm_/$id/edit': typeof CrmIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amc'
    | '/billing'
    | '/crm'
    | '/inventory'
    | '/leads'
    | '/login'
    | '/products'
    | '/quotations'
    | '/reports'
    | '/service'
    | '/settings'
    | '/suppliers'
    | '/technicians'
    | '/warranty'
    | '/crm/new'
    | '/crm/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amc'
    | '/billing'
    | '/crm'
    | '/inventory'
    | '/leads'
    | '/login'
    | '/products'
    | '/quotations'
    | '/reports'
    | '/service'
    | '/settings'
    | '/suppliers'
    | '/technicians'
    | '/warranty'
    | '/crm/new'
    | '/crm/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/amc'
    | '/billing'
    | '/crm'
    | '/inventory'
    | '/leads'
    | '/login'
    | '/products'
    | '/quotations'
    | '/reports'
    | '/service'
    | '/settings'
    | '/suppliers'
    | '/technicians'
    | '/warranty'
    | '/crm_/new'
    | '/crm_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmcRoute: typeof AmcRoute
  BillingRoute: typeof BillingRoute
  CrmRoute: typeof CrmRoute
  InventoryRoute: typeof InventoryRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  ServiceRoute: typeof ServiceRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  TechniciansRoute: typeof TechniciansRoute
  WarrantyRoute: typeof WarrantyRoute
  CrmNewRoute: typeof CrmNewRoute
  CrmIdEditRoute: typeof CrmIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amc': {
      id: '/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/new': {
      id: '/crm_/new'
      path: '/crm/new'
      fullPath: '/crm/new'
      preLoaderRoute: typeof CrmNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/$id/edit': {
      id: '/crm_/$id/edit'
      path: '/crm/$id/edit'
      fullPath: '/crm/$id/edit'
      preLoaderRoute: typeof CrmIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmcRoute: AmcRoute,
  BillingRoute: BillingRoute,
  CrmRoute: CrmRoute,
  InventoryRoute: InventoryRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  ServiceRoute: ServiceRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  TechniciansRoute: TechniciansRoute,
  WarrantyRoute: WarrantyRoute,
  CrmNewRoute: CrmNewRoute,
  CrmIdEditRoute: CrmIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
